# Generated by Django 5.2.5 on 2025-09-07 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_booking_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='day',
            new_name='date',
        ),
    ]
