# Generated by Django 5.2.5 on 2025-09-08 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_alter_room_capacity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='date',
            new_name='day',
        ),
    ]
