# Generated by Django 5.2.5 on 2025-09-09 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_rename_date_booking_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='image_url',
            field=models.URLField(blank=True, default='https://files.catbox.moe/yl6dot.jpg', max_length=500),
        ),
    ]
