# Generated by Django 5.2.5 on 2025-09-10 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_room_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='image_url',
            field=models.URLField(blank=True, default='https://i.ibb.co/W4Bjq1tG/elementor-placeholder-image.jpg', max_length=500),
        ),
    ]
