# Generated by Django 5.2.5 on 2025-09-11 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_alter_room_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday')], unique=True)),
            ],
            options={
                'ordering': ['day_of_week'],
            },
        ),
        migrations.AddField(
            model_name='room',
            name='restricted_days',
            field=models.ManyToManyField(blank=True, help_text='Select days when this room is NOT available for booking.', to='bookings.day'),
        ),
    ]
