# Generated by Django 5.2.5 on 2025-09-11 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_day_room_restricted_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.IntegerField(choices=[(9, '09:00'), (10, '10:00'), (11, '11:00'), (12, '12:00'), (13, '13:00'), (14, '14:00'), (15, '15:00'), (16, '16:00'), (17, '17:00')], unique=True)),
            ],
            options={
                'ordering': ['time'],
            },
        ),
        migrations.RemoveField(
            model_name='room',
            name='restricted_days',
        ),
        migrations.CreateModel(
            name='RoomRestriction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookings.day')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restrictions', to='bookings.room')),
                ('time_slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookings.timeslot')),
            ],
            options={
                'unique_together': {('room', 'day', 'time_slot')},
            },
        ),
    ]
